import { c as create_ssr_component } from "../../../chunks/ssr.js";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: ".panel.svelte-1rftog7{border:1px solid var(--panel-border);background:var(--panel);border-radius:20px;padding:1.2rem;box-shadow:var(--shadow);margin-bottom:1rem}.eyebrow.svelte-1rftog7{margin:0;color:var(--accent);font-weight:700;font-size:0.78rem;text-transform:uppercase;letter-spacing:0.06em}h1.svelte-1rftog7{margin:0.35rem 0 0.65rem}p.svelte-1rftog7{margin:0;color:var(--muted);line-height:1.6}.toolbar.svelte-1rftog7{display:flex;gap:0.6rem;margin-bottom:0.8rem}select.svelte-1rftog7,button.svelte-1rftog7{border:1px solid var(--panel-border);background:rgba(148, 163, 184, 0.08);color:var(--text);border-radius:10px;padding:0.55rem 0.7rem}button.svelte-1rftog7{background:linear-gradient(135deg, var(--accent), var(--accent-2));color:#f8fafc;border:0;font-weight:600}.table-wrap.svelte-1rftog7{overflow:auto}table.svelte-1rftog7{width:100%;border-collapse:collapse;min-width:640px}th.svelte-1rftog7,td.svelte-1rftog7{text-align:left;padding:0.6rem;border-bottom:1px solid var(--panel-border);color:var(--muted)}th.svelte-1rftog7{color:var(--text)}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<section class="panel svelte-1rftog7" data-svelte-h="svelte-4paks3"><p class="eyebrow svelte-1rftog7">Админ-панель</p> <h1 class="svelte-1rftog7">Заявки и статусы</h1> <p class="svelte-1rftog7">Минимальный демонстрационный вид CRM: список лидов, текущий статус и быстрые действия.</p></section> <section class="panel svelte-1rftog7"><div class="toolbar svelte-1rftog7"><select class="svelte-1rftog7"><option value="Все статусы" data-svelte-h="svelte-1qemx10">Все статусы</option><option value="new" data-svelte-h="svelte-yind6o">new</option><option value="in_progress" data-svelte-h="svelte-1sfohuf">in_progress</option><option value="closed" data-svelte-h="svelte-ducqy8">closed</option></select> <button class="svelte-1rftog7" data-svelte-h="svelte-1vynod9">Экспорт CSV</button></div> <div class="table-wrap svelte-1rftog7" data-svelte-h="svelte-3ddase"><table class="svelte-1rftog7"><thead><tr><th class="svelte-1rftog7">Дата</th><th class="svelte-1rftog7">Имя</th><th class="svelte-1rftog7">Телефон</th><th class="svelte-1rftog7">Режим</th><th class="svelte-1rftog7">Статус</th></tr></thead> <tbody><tr><td class="svelte-1rftog7">2026-02-13</td><td class="svelte-1rftog7">Айдар</td><td class="svelte-1rftog7">+7 777 111 22 33</td><td class="svelte-1rftog7">УСН</td><td class="svelte-1rftog7">new</td></tr> <tr><td class="svelte-1rftog7">2026-02-12</td><td class="svelte-1rftog7">Мадина</td><td class="svelte-1rftog7">+7 701 555 66 77</td><td class="svelte-1rftog7">ОУР</td><td class="svelte-1rftog7">in_progress</td></tr></tbody></table></div> </section>`;
});
export {
  Page as default
};
